### ISSUE TITLE
Missing Client Definition

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/jape#13]
I found out japecheck [has been failing](https://github.com/SiaFoundation/renterd/actions/runs/6685960640/job/18164809218) for some time with the following error message:

```
Analyzer output
  /Users/runner/work/renterd/renterd/.temp/check.exe ./alerts
  /Users/runner/work/renterd/renterd/.temp/check.exe ./api
  /Users/runner/work/renterd/renterd/.temp/check.exe ./autopilot
  /Users/runner/work/renterd/renterd/.temp/check.exe ./build
  /Users/runner/work/renterd/renterd/.temp/check.exe ./bus
  japecheck: no Client definition found
  japecheck: no Client definition found
  ```

I introduced this error a while ago when I moved the `worker` and `bus` client into their own packages and re-expose it.
- https://github.com/SiaFoundation/renterd/blob/master/bus/bus.go#L37
- https://github.com/SiaFoundation/renterd/blob/master/worker/worker.go#L59

Is it hard to update `definesClient` to handle the new client type? 
Is it hard to make any failure fail the build stage so these errors don't go unnoticed?

**Comment by lukechampine** [comment]
Perhaps it would work with a type alias? `type Client = client.Client`?

cc @chris124567

**Comment by chris124567** [comment]
Have been working on this, there are a few problems, the biggest of which is that the Jape client definitions (`bus/client`) are in a separate package than the server definitions (`bus`).  You can pass multiple packages to the analyzer so this is in theory OK but then you get a call to Analyzer.Run for each package, so you have to store the routes globally as you go.  I tried doing this in https://github.com/SiaFoundation/jape/commits/support-separate-packages.  My changes still for instance work for https://github.com/siafoundation/explorer where the client/server are in same package but my code currently doesn't work on renterd because it seemes like you aren't supposed to use type information from a pass outside of that pass - which occurs when comparing client and server request/response types from different packages.  So you get lots of spurious errors like this:

```
$ japecheck ./bus ./bus/client
/home/christopher/prog/go/src/go.sia.tech/renterd/bus/client/accounts.go:17:66: Client has wrong request type for POST /account/:id (got <nil>, should be go.sia.tech/renterd/api.AccountHandlerPOST)
/home/christopher/prog/go/src/go.sia.tech/renterd/bus/client/accounts.go:19:5: Client has wrong response type for POST /account/:id (got <nil>, should be *go.sia.tech/renterd/api.Account)
/home/christopher/prog/go/src/go.sia.tech/renterd/bus/client/accounts.go:17:61: Client has wrong type for path parameter "id" (got <nil>, should be go.sia.tech/core/rhp/v3.Account)
... (a lot more errors like this)
```

**Comment by chris124567** [comment]
OK, should work now in `support-separate-package`.  Will make a PR tomorrow.

I get:

```
$ ../jape/check ./autopilot
<no output, success>

$ ../jape/check ./worker ./worker/client
<no output, success>

$ ../jape/check ./bus ./bus/client
-: Client missing method for POST /accounts/%s/requiressync
-: Client missing method for PUT /buckets/%s/policy
-: Client missing method for POST /accounts/%s/add
-: Client missing method for DELETE /buckets/%s
-: Client missing method for POST /accounts/%s/update
-: Client missing method for PUT /autopilots/%s
-: Client missing method for POST /accounts/%s/resetdrift
-: Client missing method for GET /autopilots/%s
-: Client missing method for POST /accounts/%s
-: Client missing method for GET /buckets/%s
-: Client missing method for POST /accounts/%s/lock
-: Client missing method for POST /accounts/%s/unlock
```

Looks like those warnings are for deprecated endpoints in `bus`.

Anyways, this will require some changes to the Github action - basically, you will have to specify which modules you want to run jape on.  So for renterd it'd be something like: [["./bus", "./bus/client"], ["./worker", "./worker/client"], ["autopilot"]] but in the YAML format.

**Comment by peterjan** [comment]
> 
> Looks like those warnings are for deprecated endpoints in `bus`.
> 
Yeah I re-added those routes temporarily. This will be removed on Friday I think.
